### ISSUE TITLE
Add error on create if a cluster config contains invalid fields

### ISSUE THREAD

**Issue by tmckayus** [radanalyticsio/oshinko-cli#42]
Currently, if a user makes a typo or remembers the name of a configuration field incorrectly, oshinko will ignore the config and proceed to create the cluster with default settings. Instead, it should return an error.

It can be somewhat tolerant by being case insensitive ... but otherwise, if a key is defined in the configmap which oshinko-core does not recognize, it should return an error.

**Comment by tmckayus** [comment]
This issue (https://github.com/radanalyticsio/oshinko-core/issues/2) has been moved from oshinko-core to oshinko-cli after the merge.

**Comment by elmiko** [comment]
i think i may have hit this when attempting to spawn a cluster.

i ran this
```
$ http http://oshinko-rest-test.shift.opb.studios/clusters name=foo                                                                                             
HTTP/1.0 502 Bad Gateway                                                                                                                                        
Cache-Control: no-cache                                                                        
Connection: close                                                                                                                                               
Content-Type: text/html                                                                                                                                         
                                                                                                                                                                
<html><body><h1>502 Bad Gateway</h1>                                                                   
The server returned an invalid or incomplete response.                                                                                                          
</body></html>
```

which should have sent just the payload of the `name` as json. the cluster was created, but the stack trace from the server looked like this:

```
$ oc logs -f dc/oshinko-rest                                                                                                                                    
2017/09/07 19:21:43 Starting oshinko-rest-server version v0.2.5-5aa709a                                                                                
2017/09/07 19:21:43 Serving oshinko rest at http://[::]:8081                                                                                                    
I0907 19:27:10.002386       8 logs.go:41] http: panic serving 172.17.0.1:33294: runtime error: invalid memory address or nil pointer dereference                
goroutine 175 [running]:                                                                                                                        
net/http.(*conn).serve.func1(0xc4202fcc80)                                                                                                                      
        /usr/local/go/src/net/http/server.go:1721 +0xd0                                                                                               
panic(0x1a2d720, 0x2a6a0f0)                                                                                                                                     
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/radanalyticsio/oshinko-cli/core/clusters.CreateCluster(0xc420286530, 0x3, 0xc420286534, 0x4, 0xc420018016, 0x1e, 0x0, 0xc42043e378, 0x2a1a0e0, 0xc420
29a660, ...)
        /go/src/github.com/radanalyticsio/oshinko-cli/core/clusters/clusters.go:447 +0xe81
github.com/radanalyticsio/oshinko-cli/rest/handlers.CreateClusterResponse(0xc420070300, 0xc4202864b0, 0x300c420847901, 0xc4202864a0)
        /go/src/github.com/radanalyticsio/oshinko-cli/rest/handlers/clusters.go:168 +0x317
github.com/radanalyticsio/oshinko-cli/rest/restapi/operations/clusters.CreateClusterHandlerFunc.Handle(0x1cff228, 0xc420070300, 0xc4202864b0, 0x29ee920, 0xc4202
864a0)
        /go/src/github.com/radanalyticsio/oshinko-cli/rest/restapi/operations/clusters/create_cluster.go:17 +0x3a
github.com/radanalyticsio/oshinko-cli/rest/restapi/operations/clusters.(*CreateCluster).ServeHTTP(0xc42020fc00, 0x2a02220, 0xc42018fba0, 0xc420070300)
        /go/src/github.com/radanalyticsio/oshinko-cli/rest/restapi/operations/clusters/create_cluster.go:49 +0x18c
github.com/radanalyticsio/oshinko-cli/vendor/github.com/go-openapi/runtime/middleware.newOperationExecutor.func1(0x2a02220, 0xc42018fba0, 0xc420070300)
        /go/src/github.com/radanalyticsio/oshinko-cli/vendor/github.com/go-openapi/runtime/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc42045a4d0, 0x2a02220, 0xc42018fba0, 0xc420070300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/radanalyticsio/oshinko-cli/vendor/github.com/go-openapi/runtime/middleware.newRouter.func1(0x2a02220, 0xc42018fba0, 0xc420070300)
        /go/src/github.com/radanalyticsio/oshinko-cli/vendor/github.com/go-openapi/runtime/middleware/router.go:80 +0x3cf
net/http.HandlerFunc.ServeHTTP(0xc4207e24c0, 0x2a02220, 0xc42018fba0, 0xc420070300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/radanalyticsio/oshinko-cli/vendor/github.com/go-openapi/runtime/middleware.specMiddleware.func1(0x2a02220, 0xc42018fba0, 0xc420070300)
        /go/src/github.com/radanalyticsio/oshinko-cli/vendor/github.com/go-openapi/runtime/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc42072eb00, 0x2a02220, 0xc42018fba0, 0xc420070300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/radanalyticsio/oshinko-cli/rest/helpers/errors.AddErrorHandler.func1(0x2a10a20, 0xc4205b22a0, 0xc420070300)
        /go/src/github.com/radanalyticsio/oshinko-cli/rest/helpers/errors/middleware.go:91 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc42072eb20, 0x2a10a20, 0xc4205b22a0, 0xc420070300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/radanalyticsio/oshinko-cli/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x2a10a20, 0xc4205b22a0, 0xc420070300)
        /go/src/github.com/radanalyticsio/oshinko-cli/vendor/github.com/rs/cors/cors.go:190 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc42072eb60, 0x2a10a20, 0xc4205b22a0, 0xc420070300)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc4207a96b0, 0x2a10a20, 0xc4205b22a0, 0xc420070300)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4202fcc80, 0x2a11f60, 0xc420598c40)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by rebeccaSimmonds19** [comment]
Is there a reason that the default config is processed before you check if the config name is different from the default one? line 187 clusterconfigs.go

**Comment by rebeccaSimmonds19** [comment]
Resolved on pr #118 and needs reviewed
